### ISSUE TITLE
hasErrors property is always true in infinite query

### ISSUE THREAD

**Issue by ebrahim-2** [KRTirtho/fl-query#56]
Hi there!

when using an infinite query `hasErrors` property is always true

**Comment by PetrKubes97** [comment]
It's possible, but I haven't tested it with infinite queries. Will take a look.

**Comment by KRTirtho** [comment]
@ebrahim-2 can you try using the GitHub source? It should be fixed already but not released yet

```yaml
fl_query:
  git:
    url: https://github.com/KRTirtho/fl-query
    path: packages/fl_query
```
